FROM node:22-alpine AS runtime

WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
COPY client/package.json ./client/package.json
COPY server/package.json ./server/package.json
RUN npm ci --omit=dev --workspace server

COPY server ./server
RUN mkdir -p ./server/uploads

WORKDIR /app/server

EXPOSE 5001

CMD ["npm", "start"]
